### PR TITLE
fix: meta title, description and links are not accurate

### LINKED ISSUE #8: bug: site title still says "Afet haritası"
## Bug Definition
Site title says "Afet haritası" we need to update it to "secim.gonullu.io"

discord username: `umut#3072`

### PR DESCRIPTION
**Pull request by andyanday33**
# Description

**discord username: bumshaqalaqa#2973**

**closes #8 **

Changes meta title, description and links inside HeadWithMeta.* components.

## Things to check before creating a PR
- [X] I have inspected my topic, checked.

## Creating PR rules
- [X] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [X] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [X] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [X] Related file selection: Only relevant files should be touched and no other files should be affected.
- [X] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [X] Clean commit history: The commits where the changes are made should be clear and organized.
- [X] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [X] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)

# How were these changes tested?

Manually.

### CODE REVIEW

File: src/components/HeadWithMeta/HeadWithMeta.constants.tsx [hunk 1]
```diff
@@ -1,14 +1,14 @@
...
+  "Ülkenin çeşitli bölgelerindeki müşahit eksikliklerini harita üzerinde ısı haritaları ile görselleştirip sandıkların gözlemcisiz kalmamasını sağlamaya çalışıyoruz.";
+export const URL = "https://secim.gonullu.io/";
 export const OG_EDGE_URL_DYNAMIC =
   "https://deprem-yardim-og-generator-eta.vercel.app/api/dynamic-image";
 export const OG_EDGE_URL_BASE =
   "https://deprem-yardim-og-generator-eta.vercel.app/api/base-image";
 export const SEO_LANG = {
-  HREF_TR: "https://afetharita.com/tr",
-  HREF_EN: "https://afetharita.com/en",
+  HREF_TR: "https://secin.gonullu.io/tr",
```
Comment (usirin) [inline src/components/HeadWithMeta/HeadWithMeta.constants.tsx]:
```suggestion
  HREF_TR: "https://secim.gonullu.io/tr",
```

File: src/components/HeadWithMeta/HeadWithMeta.constants.tsx [hunk 2]
```diff
@@ -1,14 +1,14 @@
...
+  HREF_EN: "https://secim.gonullu.şo/en",
```
Comment (usirin) [inline src/components/HeadWithMeta/HeadWithMeta.constants.tsx]:
```suggestion
  HREF_EN: "https://secim.gonullu.io/en",
```

**Review by usirin — APPROVED** [review]
💯
