### PR TITLE
fix: some intensity levels are unreadable

### LINKED ISSUE #109: bug: some intensity texts are unreadable
## Bug Definition
A clear and short text to decribe the bug.

-- Please add discord contact information
** discord username: bumshaqalaqa#2973 **

intensity

### PR DESCRIPTION
**Pull request by andyanday33**
# Description

**discord username: bumshaqalaqa#2973**

**closes #109 **

Fixes a typo in color selector hex code

### CODE REVIEW

**Review by sevilayerkan — DISMISSED** [review]
LGTM congrats ❤️

File: src/utils/intensity.ts [hunk 1]
```diff
@@ -18,11 +18,11 @@ export const intensityColorSelector = (item: string) => {
...
   switch (item) {
     case "1":
-      return "#00000";
+      return "#000000";
     case "2":
-      return "#00000";
+      return "#000000";
     case "3":
-      return "#00000";
+      return "#000000";
```
Comment (puskuruk) [inline src/utils/intensity.ts:23]: You can merge them by using the code example below:

```
export const intensityColorSelector = (item: string) => {
  switch (item) {
    case "1":
    case "2":
    case "3":
      return "#000000";
    case "4":
      return "#FE8427";
    case "5":
      return "#FE591D";
    default:
      return "#EB2032";
  }
};
```

**Review by puskuruk — APPROVED** [review]
It looks better now. Thank you 🙏
