### PR TITLE
fix(#33): fix reading initial map coordinates and zoom level from URL

### LINKED ISSUE #33: bug: Zoom data is not properly transmitted with url
## Bug Definition
Zoom data is not properly transmitted with url. Zoom data is not displayed in the same way when the link is opened in another window/tab. Ideally, when a link is shared, the desired location should be displayed in the same way as the person sharing it.

For example:
image

When we open the link in the top picture in a different place, it looks like the following:
image

-- Please add discord contact information
** discord username: notDepresseDeveloper#0919

## Bug environment
https://musahit-harita-frontend-git-pins-on-map-acikyazilim.vercel.app/

### PR DESCRIPTION
**Pull request by dgurkaynak**
# Description

- fix reading initial map coordinates and zoom level from URL

**discord username: dgurkaynak#2533**

**closes #33**

## Things to check before creating a PR
- [x] I have inspected my topic, checked.
- [x] If it is a core feature, executed detailed tests.

## Creating PR rules
- [x] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [x] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [x] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [x] Related file selection: Only relevant files should be touched and no other files should be affected.
- [x] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [x] Clean commit history: The commits where the changes are made should be clear and organized.
- [x] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

### CODE REVIEW

File: src/components/Map/LayerControl.tsx [hunk 1]
```diff
@@ -42,8 +42,8 @@ export const LayerControl = ({ locations, onMarkerClick }: Props) => {
           return (
             <HeatmapLayer
               key={idx}
-              fitBoundsOnUpdate
-              fitBoundsOnLoad
+              fitBoundsOnUpdate={false}
+              fitBoundsOnLoad={false}
```
Comment (usirin) [inline src/components/Map/LayerControl.tsx:46]: This line was causing map to zoom out to fit all of the heatmap onto the viewport.

**Review by usirin — APPROVED** [review]
